### ISSUE TITLE
Response generation model is poor

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#10]
The current model for generating responses in the server is to construct a complete `GASearchVariantsResponse` object and to then convert this to a JSON string. This is a poor model because it entails creating lots of intermediate objects and lists of `GAVariants` and `GACalls`. This can consume large amounts of memory on the server and is a factor in the current poor performance when returning large numbers of calls. It would be much better if we could generate the JSON directly and write this to a buffer, without generating the lists of `GAVariants` and `GACalls`.

We need:

- An abstraction that lets us write JSON encoded attributes directly to the buffer. We should also bear in mind we'll want to implement [partial responses](https://developers.google.com/discovery/v1/performance) at some point. This also feeds into issue #5 where we should keep this problem in mind when generating the protocol element classes from Avro. 
- Management of the number of records written to the buffer according to the requested page size and `nextPageToken` handling.
- An approximate limit in bytes over which the response cannot grow. If we exceed this limit while generating a record, we terminate the response once the current record has been completed. This allows us to limit server memory resources and manage latency.

We should also keep the ability to directly convert protocol elements to JSON though, as this is useful for clients.

**Comment by jeromekelleher** [comment]
I'm a big fan of generators @bartgrantham, and I definitely would like to see them used here. As I outlined above, I think a function `getVariants(request)` which is a generator over all the variants in a request (for example) would simplify things a lot. However, I worry about having generators all the way down, as I don't know how we would handle errors in this case. Suppose an error occured while generating the 100th variant in a list, and Flask had already started writing the HTTP response to the socket. How would we handle this error then? 

For this reason I think it's better to fill a buffer with the response which we only write back to the client when it's complete. This way we can properly handle errors whenever they occur.

Thanks for the links above though; I think this is exactly what we'll want when we're serving reference sequences. The approach in the protocol is quite clunky at the moment, and HTTP streaming would seem to be a much simpler solution (as discussed with @cassiedoll and @calbach a while back).

**Comment by pgrosu** [comment]
The HTTP streaming discussion seems to skip my memory.  Could you point me to it so I refresh my mind? :)

Thanks,
~p

**Comment by jeromekelleher** [comment]
Discussion happened offline @pgrosu --- it'll become a PR on the schemas repo at some point.

**Comment by pgrosu** [comment]
Ah!  Sounds good, I was just wondering if it had anything to do with something along these lines:

http://flask.pocoo.org/docs/0.10/patterns/streaming/

https://docs.python.org/3/library/asyncio-stream.html#tcp-echo-client-using-streams

Thanks,
~p

**Comment by bartgrantham** [comment]
@pgrosu, the first link is what I had in mind.  I've found that using generators this way makes for surprisingly concise and simple code, but you have to commit to the concept.  @jeromekelleher makes an excellent point, though: in order to provide an error properly (ie. in the HTTP header), you need to basically run the entire computation.  I suppose that an abuse of something like "206 Partial Content" or WebDAV's "207 Multi-Status" is possible, but yikes.

Seems like that's the bottom line.  Unless the API accommodates "in-band" error reporting in the body to account for late errors, the result of the entire computation needs to be known before the first response.  That would be a sophisticated API feature.  Perhaps at some point we can propose it as an option for clients to notify the server that `streaming_ok: true`.

**Comment by pgrosu** [comment]
@bartgrantham, I agree, but are we not also going to be implementing GUCD (digests) as well, based on this post:

https://github.com/ga4gh/schemas/issues/167

Then we can request a checksum to also be performed, in order to compare against the digests which were pre-calculated.  Below is a link regarding requesting a checksum on stream:

http://flask.pocoo.org/docs/0.10/patterns/requestchecksum/

If there is a difference, then we know an error has occurred, and then that sub-portion of the data/bucket can be requested again.  I mention sub-portion, since I assume this will be performed asynchronously in parallel.

~p

**Comment by bartgrantham** [comment]
@pgrosu, I'm not sure I follow.  GUCD should be useful for the usual content addressable storage reasons, but in the case of the server aborting the middle of a response I'm not sure how it could help. 

Either the client already has the digest and the server recognizes it, in which case the server (or more likely it's caching proxy) will shortcircuit the computation and send back a 304.  Or the client doesn't have a digest (intuitively to me this feels like 99% of the cases) or the server doesn't recognize it and one will have to be generated based on the content streaming back, which won't be known until it is complete.

The flask checksum page you link to is about checksumming the raw input to the server, not the data that a server returns to the client.

**Comment by pgrosu** [comment]
Hi Bart,

So Google published a nice paper about a year ago called *MillWheel: Fault-Tolerant Stream Processing at Internet Scale*, which you can get here:

http://research.google.com/pubs/archive/41378.pdf

Simplifying a few concepts from that paper, I wrote a small *streamed client* and *server* Python program that I provided the code for at the end of this post.

Now let me give a little overview regarding this.  So imagine that you have a Variant record corresponding to a row from a VCF file.  Now let's say that within `Wormtable` that each record would also store the checksum-digest, which was hashed using SHA1.  This is a little overkill, but it's just for illustrative purposes.  Later it would be across buckets for a collection such as a VariantSet, which is sharded by a subsets of the data and could be stored as a column-based tree such as Parquet - see [Apache Parquet](http://parquet.incubator.apache.org/documentation/latest/) and [Storing and Querying Tree-Structured Records in Dremel](http://research.google.com/pubs/archive/43119.pdf) also from Google.  This would provide parallelization and scalable capabilities.

Now back to the example above.  So suppose that a Variant is stored along with its corresponding digest - the `...` is to illustrate that the stored information is longer than shown:

| Variant                            | Checksum_HexDigest |
|--- | --- |
| 2      4370   rs6057    G    A       29   .      NS=2;DP=13;AF=0.5;DB;H2 ... | 5b824ff1b7067e8f3a1982db6abbabf3765f4693  |

Now let's say you request a `VariantSet` from the server, but each `Variant` is processed individually.  I am illustrating in my example one `Variant` that will be transmitted and checked.  The format that any data will be transmitted is in the following tuple format:

```
(key, value, checksum_digest)
```

Below are the definitions for each element in the tuple:

```
            key => Describes the type of request, or required metadata
          value => The data of the request 
checksum_digest => This will be the checksum digest
```

The `key` might not be necessary for now and can be set to `null`, but is there in case additional information is helpful regarding the data that should be sent.  Now when you perform a request from the server, you will go through the following step-by-step procedure - my current *client* code implementation requests the whole record again instead of by checksum_digest value:

![checksum](https://cloud.githubusercontent.com/assets/6555937/5643384/f0a439da-9625-11e4-80d0-7be97e1cd5cb.png)

Below is the code for the *server* using a stream:

```
from flask import Flask, request, json, Response
import hashlib

app = Flask(__name__)

checksum = hashlib.sha1()
key   = "vcf.row.3"
value = "2      4370   rs6057    G    A       29   .      NS=2;DP=13;AF=0.5;DB;H2           GT:GQ:DP:HQ 0|0:48:1:52,51 1|0:48:8:51,51 1/1:43:5:.,."
checksum.update(value)
variant_data = { 'key':          key,
                 'value':        value,
                 'checksum_sha1_hexdigest': checksum.hexdigest()
               }

@app.route("/variant", methods=['GET'])
def api_variant():
    return json.dumps(variant_data)

@app.route('/stream/variant', methods=['GET'])
def api_stream_variant():
    def generate():
        for key in variant_data:
            yield json.dumps({key:variant_data[key]})
    return Response(generate())

if __name__ == '__main__':
    app.run(debug = False)


```

Below is the code for the corresponding *client*:

```
import urllib2
import hashlib
import json

stream_server = "http://127.0.0.1:5000/stream/variant"
checksum = hashlib.sha1()

variant_stream = urllib2.urlopen(stream_server).read()
variant_data = {}

parsedCompleteStream = False

while not(parsedCompleteStream):
  try:
    variant_index = variant_stream.index("}",0)
    variant_key_value = json.loads(variant_stream[:variant_index+1])
    variant_stream = variant_stream[variant_index+1:]
    for key in variant_key_value:
      variant_data[key] = variant_key_value[key]
  except:
    parsedCompleteStream = True

isChecksumVerified = False

while not(isChecksumVerified):
  key = variant_data['key']
  value = variant_data['value']
  checksum_sha1_hexdigest = variant_data['checksum_sha1_hexdigest']

  checksum.update(value)

  if ( checksum_sha1_hexdigest == checksum.hexdigest() ):
    print "\nData is valid!\n"
    print "The variant record is: \n"
    print value
    isChecksumVerified = True    
```

To run the program, first launch the *server* code and then the *client* code, and you should see the following result in the *client* window:

```
$ python client.py

Data is valid!

The variant record is:

2      4370   rs6057    G    A       29   .      NS=2;DP=13;AF=0.5;DB;H2           GT:GQ:DP:HQ 0|0:4
8:1:52,51 1|0:48:8:51,51 1/1:43:5:.,.

$
```

Hope it helps,
Paul

**Comment by Naburimannu** [comment]
Since 72cf1569c4fcdf1133d865f73df601212c708e82 landed, memory bloat is still a problem.
In handleHTTPPost() heapy only sees 32MB of string, but inside Backend:runSearchRequest() the heap dump looks like:

Partition of a set of 1254079 objects. Total size = 403036376 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 250400  20 262419200  65 262419200  65 dict of ga4gh._protocol_definitions.GACall
     1 250575  20 70172520  17 332591720  83 dict (no owner)
     2 501524  40 54219616  13 386811336  96 list
     3 250400  20 16025600   4 402836936 100 ga4gh._protocol_definitions.GACall
     4    100   0   104800   0 402941736 100 dict of ga4gh._protocol_definitions.GAVariant

runSearchRequest() builds up pageList [], then converts that list to JSON in the return statement. Since we don't have streaming yet, I suspect the easiest way to improve this memory spike would still be to convert each element of the list to JSON when it's generated, as in Jerome's Dec 15th comment.

**Comment by jeromekelleher** [comment]
Good - I get very suspicious when problems seem to just go away! I think  converting each element of the list to JSON as we go would certainly be an improvement, and we can try something more sophisticated later if it's not enough. Shall we try this out once you've landed your memory profiling and benchmarking patches?
