### ISSUE TITLE
Pin exact versions of all libraries in setup.py

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1006]
See https://github.com/ga4gh/server/issues/1003 and https://github.com/ga4gh/server/pull/1004

**Comment by reece** [comment]
Have you considered a requirements file instead?

To the extent that there's a convention, setup.py (install_requires) is best used to define the minimal package dependencies, typically unversioned. It is these dependencies that one would get with `python setup.py develop`, for example. In rare cases, you might pin as >1.2.3 if you know that there's a bug fixed in a particular version. For hgvs, I tell people to pin as >=0.4, <0.5, which means the'll get the 0.4.x patches, but won't inadvertently upgrade to 0.5 (which will have api changes).

Requirements files are the more conventional place to pin exact versions, often based on functional testing and QC team validation.

Because pinning may have implications for package consumers, it's best to let applications pin versions and to NOT do so in library packages. (Imagine the mess when A depends on B and C, and B and C specify incompatible versions of D.)

https://python-packaging-user-guide.readthedocs.org/en/latest/requirements/

**Comment by dcolligan** [comment]
Fixed in #1010
