### ISSUE TITLE
Using ':' as a separator in CompoundIds is problematic. Replace.

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1018]
See discussion at https://github.com/ga4gh/server/pull/999#discussion_r57175788

It should be possible to replace easily enough. Suggestions?

**Comment by diekhans** [comment]
Don't try to choose a safe delimter, insead encode each
component so that the chosen delimiter can't collide: For
instance:

   `:' -> `\:'
   `\\' -> `\'

since it's all done in one place, this should be transparent.

**Comment by macieksmuga** [comment]
I agree with Mark, there is no safe delimiter - I'd much rather use a uniform, generic mechanism (bundled with the Compound ID object) for escaping the delimiter.

**Comment by macieksmuga** [comment]
FYI, since the latest refactor of the Sequence Annotation PR #999 - I no longer have a problem with special characters in IDs (as all internal IDs for features have now been replaced with unique long integers). So while I still agree with Mark's general suggestion, this issue is no longer a blocker on any of my current code.

**Comment by dcolligan** [comment]
Fixed in #1042
