### ISSUE TITLE
Support multiple test buckets

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/server#106]
We should have wicked fast unit tests; the current set is perhaps a bit slow.
Separate from those we should have integration tests.
Separate from those we should have end-to-end tests.

We should make sure Travis runs at least some of the end-to-end tests on merge.
(If we get wheels to help with #71 that'll win us some time for more aggressive testing per merge.)

**Comment by melaniedc** [comment]
+1 

I would say there should be one very basic end-to-end test in Travis just to make sure everything fits together and doesn't explode, then separate integration tests with the real test cases that can run less frequently.

**Comment by jeromekelleher** [comment]
Yep, all very sensible. The slowest aspect of the tests at the moment is creating the wormtable test fixtures, as we convert the input VCF data. As part of our mission to get rid of wormtable, we should try to get rid of these fixtures and use something based on pysam instead.

**Comment by dcolligan** [comment]
So there seem to be a few ways that we could do this:

1) Tagging.  Use decorators to tag each test https://nose.readthedocs.org/en/latest/plugins/attrib.html
2) Classes.  Each test doesn't inherit from unittest.TestCase, but one of several pre-defined classes like ga4gh.tests.IntegrationTest or some such.
3) Directories.  Have several directories inside of the test directory `unit`, `integration`, etc.  Place each test file in the appropriate subdirectory.

3 sounds easiest to me, since it involves minimal code changes and habit changing.

**Comment by dcolligan** [comment]
On the other hand, 3 would be bad if we want the same test to run under multiple configurations (or, at least, we would need to use 1 or 2 in addition to 3).  I'm not sure how crazy we want to get with test configurations.

**Comment by Naburimannu** [comment]
Sounds like we should do #3 now, and if we have a more complex use case
really needed look into doing the additional work for #2 or #1?

**Comment by jeromekelleher** [comment]
I'd vote for option 3 also.

**Comment by dcolligan** [comment]
Fixed in #157
