### ISSUE TITLE
logging exceptions should not be controlled by DEBUG and should default to enabled

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#1099]
It would be really good for server to use the syslog (also python logging) conceptual model.  In particular, logging uncaught exceptions would not be controlled by a option called DEBUG.  This is at least level
`Error'.  This should default to `on'.

see https://en.wikipedia.org/wiki/Syslog#Severity_level

Since logging exceptions is the only thing controlled by `DEBUG',  please change this to default to True until it can be made consistent with syslog.

**Comment by kozbo** [comment]
https://github.com/ga4gh/server/blob/99aafd4b83ac4d65a73b37a152e1851b3be82f70/ga4gh/frontend.py#L343

**Comment by kozbo** [comment]
You can work around this problem by adding the line 
DEBUG=True
in the config.py file and restarting apache.

**Comment by jeromekelleher** [comment]
We should do proper logging, following the [Flask patterns](http://flask.pocoo.org/docs/0.10/errorhandling/)

Turning on DEBUG by default could have very serious security implications! From the [Flask documentaion](http://flask.pocoo.org/docs/0.10/quickstart/)

> Even though the interactive debugger does not work in forking environments (which makes it nearly impossible to use on production servers), it still allows the execution of arbitrary code. This makes it a major security risk and therefore it must never be used on production machines.

So, we need to find another way to work around this problem.

**Comment by diekhans** [comment]
We will be moving away from flask. Python logging, which is
based on syslog, is a far better understood model than flask.
Leave the flask variables for flask stuff and don't mix them
and they will be fine.

The problems seem to be:

  - DEBUG is not documented in the config file as something the
    controls flask, or for for that matter what it controls.
    From looking at the code, it appears to only control logging
    of exceptions.

  - Logging of exceptions (except ones reporting a user error),
    is vital for a production server.  It shouldn't be controlled
    by the DEBUG variable.

**Comment by jeromekelleher** [comment]
I'm pretty sure that the logging exceptions thing is a side-effect of us working around some other stupid issue in Flask (possible what Kevin is hitting).

However, the server IS a Flask app, for better or worse. We can't ignore the fact that it is, and a administrator can't deploy safely or sensibly without knowing how Flask configuration works and what the overall options are. Pretending Flask isn't there will just end up making things worse. So, for production, we need to understand how Flask works, and  work with it rather than against it.

**Comment by diekhans** [comment]
I am not arguing for pretending it isn't there, only making it
clear that is it and what is flask and what is not.  I just
filed a bug on config.py documentation as it doesn't describe
DEBUG at all, even say `RTFM Flask'

If we have our own logging, it doesn't need to be he tied to
flask, but would be to have a clear model and go through the
python logging API, even if this ends up in the flask log.

In fact, this is a non-issue:
   http://flask.pocoo.org/docs/0.10/errorhandling/

   "Flask uses the Python builtin logging system,"

so the real problem is we are misusing (and not documenting) the DEBUG
config.py option.

**Comment by jeromekelleher** [comment]
OK, here's our actual manual @diekhans: http://ga4gh-reference-implementation.readthedocs.org/en/stable/configuration.html#configuration-file

We do not attempt to document any of Flask's config variables but instead point the user to the Flask documentation. Note the ..warning block about DEBUG. I think this confusion has been caused by reading the source rather than reading the manual.

**Comment by diekhans** [comment]
RTFM, who, me !?!?!

I am reading the config file!  A pointer back to the doc in the
config file would solve this nicely.
