### ISSUE TITLE
What is the correct mapping VCF GT values to `Call` objects?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#14]
The mapping VCF genotype values to GA4GH `Call` objects  is currently incomplete/incorrect. Questions:

1. If the delimiter is `|` then the genotype is phased. What should the value of the `phaseset` field be? If the delimiter is `/` then I assume phaseset should be null.
2. What does ./. indicate in terms of `Call` objects? No call exists an so we do not return a `Call` for the current `CallSet`?

**Comment by mbaudrey** [comment]
I'm working on this issue and I'm a bit unclear on some of the specifications.

1. For genotypes containing periods, are only `.` and `.\.` valid inputs? It seems to me that we should also allow genotypes that contain both integers and periods, such as `1/.` or `.|0`, for flexibility. But perhaps it isn't possible for a call to be made on one allele and not the other?

If this format of genotype should be allowed, how would we represent it internally? Currently a standard genotype such as `1` or `0/2` would be represented as a list of the integers it contains (`[1]` or `[0, 2]`) and any genotype containing a period would be represented as `[-1]` regardless of the presence of multiple periods, delimiters, or integers.

If we do allow mixed integers and periods, it the simplest solutions is that the `.`, rather than the entire genotype, should be replaced with a `-1`. So the genotype `1/.` would be represented as `[1, -1]`.

2. What do phase set values mean and how should they be stored? The specifications of VCF format only clarify that the PS field should contain a 32-bit integer and that genotypes with the same value are in the same phase set.

**Comment by richarddurbin** [comment]
For VCF and the current Variant model I think we can safely rule out mixed integer and . genotypes.  Normally the total sum count is known/implicit, e.g. when diploid 1|. must be 1|1 because the allele counts must sum to 2.
So Cassie's rules that if there is any dot then call the genotype as missing seem OK to me.  We can add a note to this effect.

Richard

On 7 Jan 2015, at 19:52, mbaudrey <notifications@github.com> wrote:

> I'm working on this issue and I'm a bit unclear on some of the specifications.
> 
> For genotypes containing periods, are only . and .\. valid inputs? It seems to me that we should also allow genotypes that contain both integers and periods, such as 1/. or .|0, for flexibility. But perhaps it isn't possible for a call to be made on one allele and not the other?
> If this format of genotype should be allowed, how would we represent it internally? Currently a standard genotype such as 1 or 0/2 would be represented as a list of the integers it contains ([1] or [0, 2]) and any genotype containing a period would be represented as [-1] regardless of the presence of multiple periods, delimiters, or integers.
> 
> If we do allow mixed integers and periods, it the simplest solutions is that the ., rather than the entire genotype, should be replaced with a -1. So the genotype 1/. would be represented as [1, -1].
> 
> What do phase set values mean and how should they be stored? The specifications of VCF format only clarify that the PS field should contain a 32-bit integer and that genotypes with the same value are in the same phase set.
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by bioinformed** [comment]
I won't advocate for any specific solution.  However I will point out that
nothing in the VCF spec precludes partially missing genotypes
(syntactically or semantically) and there are many VCF files in the wild
with partial calls (mostly from CGI data which include "half calls").

-Kevin

**Comment by richarddurbin** [comment]
That is interesting.  I wander what they do intend to mean by a half call.  Can you send some examples?
I guess they could be using ".|1" to indicate at least one alternative allele, i.e. "1|1 or 0|2", but I am not 
sure that we should support that semantics indicated that way.  Perhaps once we have examples we could
ask CG what they mean.

Richard

On 7 Jan 2015, at 22:40, Kevin Jacobs <notifications@github.com> wrote:

> I won't advocate for any specific solution. However I will point out that 
> nothing in the VCF spec precludes partially missing genotypes 
> (syntactically or semantically) and there are many VCF files in the wild 
> with partial calls (mostly from CGI data which include "half calls"). 
> 
> -Kevin 
> 
> 
> On Wed, Jan 7, 2015 at 1:01 PM, Richard Durbin <notifications@github.com> 
> wrote: 
> 
> > For VCF and the current Variant model I think we can safely rule out mixed 
> > integer and . genotypes. Normally the total sum count is known/implicit, 
> > e.g. when diploid 1|. must be 1|1 because the allele counts must sum to 2. 
> > So Cassie's rules that if there is any dot then call the genotype as 
> > missing seem OK to me. We can add a note to this effect. 
> > 
> > Richard 
> > 
> > On 7 Jan 2015, at 19:52, mbaudrey <notifications@github.com> wrote: 
> > 
> > > I'm working on this issue and I'm a bit unclear on some of the 
> > specifications. 
> > > 
> > > For genotypes containing periods, are only . and .\. valid inputs? It 
> > seems to me that we should also allow genotypes that contain both integers 
> > and periods, such as 1/. or .|0, for flexibility. But perhaps it isn't 
> > possible for a call to be made on one allele and not the other? 
> > > If this format of genotype should be allowed, how would we represent it 
> > internally? Currently a standard genotype such as 1 or 0/2 would be 
> > represented as a list of the integers it contains ([1] or [0, 2]) and any 
> > genotype containing a period would be represented as [-1] regardless of the 
> > presence of multiple periods, delimiters, or integers. 
> > > 
> > > If we do allow mixed integers and periods, it the simplest solutions is 
> > that the ., rather than the entire genotype, should be replaced with a -1. 
> > So the genotype 1/. would be represented as [1, -1]. 
> > > 
> > > What do phase set values mean and how should they be stored? The 
> > specifications of VCF format only clarify that the PS field should contain 
> > a 32-bit integer and that genotypes with the same value are in the same 
> > phase set. 
> > > — 
> > > Reply to this email directly or view it on GitHub. 
> > > 
> > 
> > 
> > 
> > 
> > -- 
> > The Wellcome Trust Sanger Institute is operated by Genome Research 
> > Limited, a charity registered in England with number 1021457 and a 
> > company registered in England with number 2742969, whose registered 
> > office is 215 Euston Road, London, NW1 2BE. 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/ga4gh/server/issues/14#issuecomment-69091255>. 
> >
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jeromekelleher** [comment]
It sounds like we can probably follow Cassies approach above for question (1) safely enough for now, and put in some comments noting the issues that @bioinformed  brought up above. I'm afraid I can't shed any light on question (2) though; would someone else like to weigh in here?

**Comment by bioinformed** [comment]
My understanding is that a half-call in a diploid region is made when:

   1. there is no evidence of a large deletion or duplication that would
   alter the effective ploidy of the region,
   2. one allele (ref or alt) can be called with sufficiently high
   confidence to report as a hard-call, and
   3. no single diploid hypothesis is sufficient to generate a hard-call
   for the second allele.

Obviously not all genotyping models are able to generate such nuanced
inferences.  The primary utility in VCF and BCF is to express the
confidently called allele, the inferred ploidy of the locus and establish
the cardinality of the remaining genotype data fields (particularly
genotype likelihoods, which can provide information on which alternative
hypotheses are plausible).  The zygosity of a half-call should treated as
uncertain.

Personally, I find half-calls to be useful and elegant (but clearly not
necessary).  Both the VCF and BCF specs (and their respective htslib parser
implementations) accept mixtures of missing and specified alleles.
However, I also believe that it would cause little harm if the GA4GH API
simplified these semantics by treating partially called genotypes as fully
missing, provided that ploidy is preserved and zygosity is reported as
unknown.

I'll look for examples of half-calls in VCF files in the wild.  I know I've
written code that generates such calls when converting CG data to VCF, but
I don't remember offhand if CG's more recent mkvcf tool does.  I've Cc'd
Rich Tearle from CG to (hopefully) comment more directly on their evolving
views on the utility of half-calls.

-Kevin

**Comment by lh3** [comment]
I have only seen half calls from CG data, not elsewhere. I guess this has something to do with their assembly-based calling. Half calls are a bit unfortunate in data processing because many tools don't handle them well. It also adds more scenarios to consider. The benchmark team was considering complex comparisons involving half calls.

I think the right way is to arbitrarily call out two alleles, as all the other callers do, and assign confidence values to genotypes or potentially to individual alleles - somehow related to the unary model. Nonetheless, this might be difficult to the CG caller.

**Comment by mbaudrey** [comment]
So it seems to me that there is some ambiguity as to whether we should expect half-calls or not. It seems to me that for flexibility the solution I suggested above (`./.` represented as `[-1,-1]`, etc.) should work fine and is still consistent with the API. Are there any reasons that it would cause problems?

Also - @richarddurbin why must the numbers sum to 2? They are just a number representing a particular alternate genotype.

**Comment by haussler** [comment]
good suggestion Heng

**Comment by bioinformed** [comment]
Kevin,

Sorry to take so long to get back to you, have been on vacation.

Your points 2 and 3, concerning why we make half calls, are correct.

For point 1, it would only be true for deletions up to ~100bp.
These are the deletions that are called as part of the small variant
calling pipeline.
And in those cases the ploidy is explicitly reported.
Any larger deletion called from our CNV or SV pipelines is not factored in.
This is mainly because the likelihood of them being correct is not as high.
Ideally we would use them, but we don't trust the large variant data enough
right now.

I agree with most of your points concerning half-calls.
But I am not so sure about taking a half-called locus and making it fully
no-called.
We may have strong evidence supporting a variant allele eg 23 A reads.
We may have 4 reads supporting the reference allele eg C.
So under a Bayesian model, A/A and A/C may have similar levels of support.
And this leads us not to call the 2nd allele, because we are unsure if it
is an A or C.
However the first allele is clearly an A.
It would be a pity to throw this information away.
I would prefer to call the doubtful 2nd allele instead, to report the whole
genotype.

We have been thinking about this a lot lately, as we redesign our pipeline.
The following are just my thoughts at the moment, nothing in stone.

We want to separate reporting from interpreting.
I consider calling the variant as reporting, imposing a filter as
interpreting.

To this end, we will call variants, even with little evidence.
So for almost all positions we will report something, reducing the number
of half- and no-calls.
The really weakly supported calls will naturally have a low score.
We will use the score to apply a filter eg Low Quality.

That way we report pretty much everything.
But also provide the filter to warn users not to trust the more weakly
supported calls.

I think this is a better way to go.
But it means we have to ensure we educate less sophisticated users.
Otherwise they may take all calls at face value.

One use case is that when comparing genomes, there are very few no-calls.
So a user can compare calls at the same position in eg related genomes.
It also means that users can impose their own filters.
In some cases they will want to remove low quality calls eg looking for de
novos.
In some cases they will probably not care at all eg case control analysis.

Does that make sense?

Overall, I do think the rationale for half calls exists.
But in most cases they probably can be avoided.
My only concern is that the quality of the calls is reported adequately,

Rick


On Fri, Jan 9, 2015 at 4:06 AM, Kevin Jacobs <jacobs@bioinformed.com> wrote:

> My understanding is that a half-call in a diploid region is made when:
>
>    1. there is no evidence of a large deletion or duplication that would
>    alter the effective ploidy of the region,
>    2. one allele (ref or alt) can be called with sufficiently high
>    confidence to report as a hard-call, and
>    3. no single diploid hypothesis is sufficient to generate a hard-call
>    for the second allele.
>
> Obviously not all genotyping models are able to generate such nuanced
> inferences.  The primary utility in VCF and BCF is to express the
> confidently called allele, the inferred ploidy of the locus and establish
> the cardinality of the remaining genotype data fields (particularly
> genotype likelihoods, which can provide information on which alternative
> hypotheses are plausible).  The zygosity of a half-call should treated as
> uncertain.
>
> Personally, I find half-calls to be useful and elegant (but clearly not
> necessary).  Both the VCF and BCF specs (and their respective htslib parser
> implementations) accept mixtures of missing and specified alleles.
> However, I also believe that it would cause little harm if the GA4GH API
> simplified these semantics by treating partially called genotypes as fully
> missing, provided that ploidy is preserved and zygosity is reported as
> unknown.
>
> I'll look for examples of half-calls in VCF files in the wild.  I know
> I've written code that generates such calls when converting CG data to VCF,
> but I don't remember offhand if CG's more recent mkvcf tool does.  I've
> Cc'd Rich Tearle from CG to (hopefully) comment more directly on their
> evolving views on the utility of half-calls.
>
> -Kevin
>
>
> On Thu, Jan 8, 2015 at 2:22 AM, Richard Durbin <notifications@github.com>
> wrote:
>
>> That is interesting. I wander what they do intend to mean by a half call.
>> Can you send some examples?
>> I guess they could be using ".|1" to indicate at least one alternative
>> allele, i.e. "1|1 or 0|2", but I am not
>> sure that we should support that semantics indicated that way. Perhaps
>> once we have examples we could
>> ask CG what they mean.
>>
>> Richard
>>
>> On 7 Jan 2015, at 22:40, Kevin Jacobs <notifications@github.com> wrote:
>>
>> > I won't advocate for any specific solution. However I will point out
>> that
>> > nothing in the VCF spec precludes partially missing genotypes
>> > (syntactically or semantically) and there are many VCF files in the
>> wild
>> > with partial calls (mostly from CGI data which include "half calls").
>> >
>> > -Kevin
>> >
>> >
>> > On Wed, Jan 7, 2015 at 1:01 PM, Richard Durbin <
>> notifications@github.com>
>> > wrote:
>> >
>> > > For VCF and the current Variant model I think we can safely rule out
>> mixed
>> > > integer and . genotypes. Normally the total sum count is
>> known/implicit,
>> > > e.g. when diploid 1|. must be 1|1 because the allele counts must sum
>> to 2.
>> > > So Cassie's rules that if there is any dot then call the genotype as
>> > > missing seem OK to me. We can add a note to this effect.
>> > >
>> > > Richard
>> > >
>> > > On 7 Jan 2015, at 19:52, mbaudrey <notifications@github.com> wrote:
>> > >
>> > > > I'm working on this issue and I'm a bit unclear on some of the
>> > > specifications.
>> > > >
>> > > > For genotypes containing periods, are only . and .\. valid inputs?
>> It
>> > > seems to me that we should also allow genotypes that contain both
>> integers
>> > > and periods, such as 1/. or .|0, for flexibility. But perhaps it
>> isn't
>> > > possible for a call to be made on one allele and not the other?
>> > > > If this format of genotype should be allowed, how would we
>> represent it
>> > > internally? Currently a standard genotype such as 1 or 0/2 would be
>> > > represented as a list of the integers it contains ([1] or [0, 2]) and
>> any
>> > > genotype containing a period would be represented as [-1] regardless
>> of the
>> > > presence of multiple periods, delimiters, or integers.
>> > > >
>> > > > If we do allow mixed integers and periods, it the simplest
>> solutions is
>> > > that the ., rather than the entire genotype, should be replaced with
>> a -1.
>> > > So the genotype 1/. would be represented as [1, -1].
>> > > >
>> > > > What do phase set values mean and how should they be stored? The
>> > > specifications of VCF format only clarify that the PS field should
>> contain
>> > > a 32-bit integer and that genotypes with the same value are in the
>> same
>> > > phase set.
>> > > > —
>> > > > Reply to this email directly or view it on GitHub.
>> > > >
>> > >
>> > >
>> > >
>> > >
>> > > --
>> > > The Wellcome Trust Sanger Institute is operated by Genome Research
>> > > Limited, a charity registered in England with number 1021457 and a
>> > > company registered in England with number 2742969, whose registered
>> > > office is 215 Euston Road, London, NW1 2BE.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/ga4gh/server/issues/14#issuecomment-69091255>.
>> > >
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>>
>>
>>
>> --
>> The Wellcome Trust Sanger Institute is operated by Genome Research
>> Limited, a charity registered in England with number 1021457 and a
>> company registered in England with number 2742969, whose registered
>> office is 215 Euston Road, London, NW1 2BE.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ga4gh/server/issues/14#issuecomment-69160959>.
>>
>
>


-- 
Dr Rick Tearle
Senior FAS
Complete Genomics
Mobile: +44 7702057554
Email: rtearle@completegenomics.com

**Comment by jeromekelleher** [comment]
This was fixed in #99.
