### ISSUE TITLE
Proposal: test to prevent bad constraints.txt files from being merged into master

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1567]
Here's something I've been thinking about.  There seems to be a constant danger of merging a modified constraints.txt file into master.  I propose we create a test that prevents this from happening:

- check in a file, `constraints.txt.default` that is a constraints.txt file that points to all of the master branches -- that is, what the `constraints.txt` file's contents in master should always be
- add a unit test that checks whether `constraints.txt.default`'s contents are identical to `constraint.txt`'s, and fail if not

Pro: would prevent check-ins of erroneous constraint.txt files to master
Con: would cause a general test failure whenever constraint.txt is modified

Opinions?  @david4096 @andrewjesaitis

**Comment by andrewjesaitis** [comment]
I think this is a great idea. I guess the alternative would be to add `constraints.txt` to `.gitignore`. I guess it depends on which tests you want to fail when submitting a pair of PR's to schemas and server.

If we unit test `constraints.txt`, I think the flow would be like:
1. Push PR to schemas - schemas test PASS
1. Push PR to server with constraints.txt pointing to schemas PR branch - server tests FAIL (because of constraints file differs)
1. Schemas PR merged
1. Update server PR with `constraints.txt` pointing at schemas@master - server tests PASS

With the `.gitignore`:
1. Push PR to schemas - schemas test PASS
1. Push PR to server; modified constraints.txt not pushed - server tests FAIL (because of missing dependency)
1. Schemas PR merged - server tests PASS

Problems with the `.gitignore` is that
* Can't easily push working demos that rely on modified `constraints.txt`
* Not sure how you kick Travis CI to rerun tests when a schemas PR is merged

I vote `constraints.txt` unit test.

**Comment by ejacox** [comment]
I think the approach sounds reasonable. Instead of a .default file, could git be used to check if the file changed? 'git diff' maybe

**Comment by dcolligan** [comment]
Fixed in #1568

**Comment by dcolligan** [comment]
Parallel PRs in

schemas: https://github.com/ga4gh/schemas/pull/817

client: https://github.com/ga4gh/ga4gh-client/pull/62
