### ISSUE TITLE
update README to include requirements.txt

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#159]
The setup described in the README is a bit out of date

**Comment by macieksmuga** [comment]
Updating it based on my recent install experience

**Comment by macieksmuga** [comment]
I wanted to get quick feedback from others before I modify the read, but here's my experience with installing the server from scratch (on a MacOS X 10.10 laptop with macports), and trying to run the nosetests:

The one external dependency not explicitly covered by the readme file is wormtable's dependency on Berkeley DB. While a link to the document that covers how to satisfy this dependency is eventually given, I was thinking of moving it up a couple of sentences in the readme, so that a first-time user following along with  the instructions doesn't get the inevitable error the first time they try to pip install wormtable.

The second thing I noticed, when running the nosetests, is that flask has presumably created a bunch of dependencies that aren't sufficiently covered by the existing requirements.txt file, namely:

mccabe, pyflakes, werkzeug, jinja2, itsdangerous, six

Unless I hear otherwise, I'll update the requirements.txt file with the above packages.

**Comment by pgrosu** [comment]
@macieksmuga, absolutely agree and everything has to be documented clearly and in a step-by-step fashion, for different OS environments on both server or local implementation with logging for debugging.  This does not need to be complete in the first iteration, and can be streamlined over time.

It took me a couple of hours of setting everything up from scratch back in December on a cluster under only user-privilege level.  It definitely has to be a turn-key solution and we can't rely on the user to have significant expertise in setting things up, since working with the implementation and possibly updating the code would have a higher priority.

Paul

**Comment by jeromekelleher** [comment]
It's probably a good idea to emphasise the Berkeley DB dependency for wormtable, as this would be a nasty stumbling block for a lot of users. We are planning on removing wormtable soon (hopefully!), so I wouldn't put too much work into this though.

For requirements.txt, I don't think there's any need to explicitly list the recursive requirements for Flask etc. Pip works these out, so we should just keep it to the list of packages that we use directly.

**Comment by macieksmuga** [comment]
Thanks @jeromekelleher and @pgrosu for your feedback! 
Concerning the automatic dependency graph in pip, it didn't quite work out the first time in my case - which is why I had to perform the above listed pip installs manually after running the initial pip install -r requirements.txt 

I realized that the reason the process failed was due to wormtable install exiting on error. Once that was fixed, the flask dependencies were loaded automatically as expected.
