### ISSUE TITLE
Need to be precise about what Python versions are supported

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#18]
The setup scripts currently do not check what Python version is being used, which leads to cryptic failures on older Python versions. This should be fixed, and the exact versions tested using Travis.

**Comment by diekhans** [comment]
Q:   Given that the server is a program, not a library, is the value of supporting python 2 worth the effort?  It takes more engineering effort and prevents taking advantage python 3 features.

"We Are Not Afraid of the Future"
--  Tomas Bata

**Comment by jeromekelleher** [comment]
I think so. Python 2.7 supports all the major improvements in Python 3 using futures, and there are a lot of people still using 2.7. I think the support cost of insisting on Python 3 would be larger than the engineering cost of keeping 2.7 support going. (Plus, we don't actually support Python 3 at the moment, but this is definitely something  we should fix soon. )

What Python 3 features did you have in mind?

**Comment by diekhans** [comment]
Single biggest feature, which I don't think is backported is
exception chaining.  That makes a huge difference in my
experience (I have been using the concept since before Java even
existed).

I don't think people using 2.7 is important, since 3.* can be
installed beside 2.*.  I care far more about your time than
people who can't figure out how to install both.

Part of being a reference server, you get to limit your audience
to people who know what they are doing.

**Comment by jeromekelleher** [comment]
Closing this as the README now states specifically we only support 2.7, and we have no immediate plans for supporting Python 3 because of upstream dependency issues.
