### ISSUE TITLE
Add "classic" compatibility mode to server for new graph version of GA4GH API 

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#183]
A new graph version of the GA4GH API was added via PR 238 in the GA4GH/schema repository:
https://github.com/ga4gh/schemas/pull/238
It supports both classic and graph-supported server modes, with some syntax changes to the classic mode as compared to the v0.51 API. 

As a first step to building a reference server for the new graph API, the current server needs to be updated to support the "classic" mode syntax of the new GA4GH schema.

**Comment by jeromekelleher** [comment]
Isn't the server currently in classic mode at the moment?

**Comment by adamnovak** [comment]
If nothing else, it needs to implement the method to advertise its support
for classic mode.

It may also need some other changes to move it from v0.5.1 to v0.6 classic
mode, as there are some non-graph-related breaking changes that other
people have made (for example, the new Strand enumeration).

**Comment by jeromekelleher** [comment]
Moving to the 0.6.0 release (whenever it comes out) will be a big step, and we'll need to resolve a bunch of issues to go through this.

**Comment by dcolligan** [comment]
@adamnovak: "If nothing else, it needs to implement the method to advertise its support
for classic mode."

What method is this?

**Comment by jeromekelleher** [comment]
This is part of the forthcoming 0.6.0 release, which we're not aiming at right now. I don't think we should implement any API methods until they are released.

There's no reason we can't get infrastructure in place to support graph mode/v0.6.0, I just don't think we should implement the _methods_ until they are released.

**Comment by lh3** [comment]
We should wait until the graph part get stabilized. We agreed that #238 is just an initial attempt. Multiple rounds of iterations are likely to be required to get it to the implementation level.

**Comment by adamnovak** [comment]
@dcolligan I'm referring to the [`sendsMode()` method](https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/referencemethods.avdl#L8). The server has to announce that it serves classic mode, and a well-behaved classic mode client should check to make sure the server serves classic mode. This is so you don't accidentally point a classic-only client at a graph-only server and crash when it tries to send you `GraphAlignments` for reads, or (worse) run successfully but get an incomplete picture of a `CallSet` you are interested in and do an incorrect downstream analysis.

I would favor having a compliant v0.6 server to release alongside the v0.6 API. I agree with @lh3 that moving the server towards that is going to be chasing a moving target until we settle on what the graph side of the API will actually look like, so it doesn't necessarily make sense to shoot for full and exact compliance with the spec immediately. But I think we should start fleshing out the implementation, including the methods. It might be best to do it in a v0.6 branch of the server repo.

We need to try implementing v0.6 so we can iterate on the schema and produce something implementable and efficient.

**Comment by benedictpaten** [comment]
I understand the need to iterate on the pull request - but, do we really want to move to branches for 0.6? If we can escape branching and make a rapid series of pull-requests maybe we can avoid having a lot of fork and merge pain while we still don't have an easy semi-complete reference server implementation. Given that it is backward compatible, we could just add it in progressively?

**Comment by jeromekelleher** [comment]
My proposal for handling the process of supporting graph mode and moving the schema forward is as follows:

1. We make a v0.6.0 release of the schema soon. I absolutely agree with @lh3 and we will need to iterate on the current spec for a while before we get to something that works well. I would suggest that we do this through a series of point releases --- we can regard 0.6.x series as a development series (with respect to graph mode; classic mode should have the usual stability requirements), since we're working on something so new and unfamiliar. While I very much agree with Heng about not wanting to implement a moving target, I also think we should get some practical experience with the graph mode to inform the design. This is why I think a series of minor point releases is a good compromise between giving us something stable to implement here, and also allow for meaningful feedback into the API design from our implementation experience.
2. To make the transition to 0.6.0 here in the reference server, we wait for the release, and then make the minimum possible PR to make things work on the new schema (I'm thinking of things like getting rid of the GA prefix, updating `process_schemas.py` and committing in the new `_protocoldefinitions.py`). We then make a set of issues required to fully support this schema, and move forward by resolving these incrementally as we go. This should ensure that we always have working server.

I agree with @adamnovak that we should aim to accompany a release of the protocol with a fully compliant release of the reference implementation. However, we have too much to do to bring ourselves up to the spec for this to be realistic for 0.6.0. It is certainly a goal I think we should aim for in future, however.

**Comment by benedictpaten** [comment]
I *strongly* +1 Jerome's vision on this.

**Comment by lh3** [comment]
@jeromekelleher currently we don't have a graph. Are you going to generate this graph, or to wait for others (e.g. @benedictpaten, @iqbal-lab and @ekg) to generate it for you?

**Comment by iqbal-lab** [comment]
I think ideally several of us either implement or partially implement and realise there are issues. I'm playing catch up, but I will try

**Comment by fnothaft** [comment]
+1 @lh3 @iqbal-lab

**Comment by jeromekelleher** [comment]
@lh3 I think we have lots of graphs, we just need to output them in a format that is compatible with the current GA4GH model. I'm pretty sure there is a simple algorithm translating the graphs that we already have into the Durbin form, so the only missing link is to define a file format to write this information to. This is something we're hoping to nail down soon. I'm arguing for a SQLite based approach for this, with a schema that is a literal translation of the Avro structures into relational form. This would make life nice and simple for us on the reference server, as there would be no need for any input data conversion step.

**Comment by ekg** [comment]
@jeromekelleher What if I sent you graphs in Durbin form to start working with? I can serialize them in a bespoke extension to the GFA format that allows for path inclusion. That's trivial to parse. It's a temporary solution, but it's enough to get started.

(@lh3 @jts -- the bespoke idea for GFA is to use "P node_id path_name" to specify paths alongside nodes; you could also have a cigar for the mapping between the path and the node. Probably we should discuss this elsewhere.)

Alternatively, I can write a parser for the on-disk vg format for your target language for the server. This is trivial to do as long as you can open a gzipped file and there is a protobuf compiler for the language. Maybe 30 lines of python.

**Comment by jeromekelleher** [comment]
Sounds great @ekg! It would be great if you could send me on a few little samples so I can start thinking about it. I'm sure we can get the data into the form we want easily, and it'll be great to make this discussion concrete.

**Comment by lh3** [comment]
@ekg I am trying to work out what GA4GH graph cannot represent. Suppose we have the following graph in the GFA format which contains four sequences A, B, C and D:
```
L  A  -  B  +  // this means the 3'-end of A joins the 5'-end of B
L  A  -  D  +
L  C  -  B  +
L  C  -  D  +
```
and that the reference path goes through A and B. I think this graph cannot be described in the GA4GH representation because end C- has two joins but each segment end in a GA4GH graph only allows one join. Is that right? If so, this calls for questions: 1) what types of graphs the GA4GH model cannot describe? 2) are we sure that we will never generate variant graphs that cannot be described by the GA4GH model? Or should we simply allow multiple end joins in GA4GH such that it can represent any GFA graphs? BTW, do we need orientation in `P node_id path_name`?

**Comment by haussler** [comment]
You can represent that graph. You would get it, for example, if AB is the
original primary path, then you add child that allows the variant CB  (a
"SNP bubble" with C in place of A), then you add a child that allows the
variant AD (a "SNP bubble" that allows D in place of B), and finally you
add an empty child that allows an adjacency between the 3' side of C and
the 5' side of D. This last child allows a single path CD.

-D

**Comment by lh3** [comment]
Are you suggesting adding an extra empty Segment between C and D? But then we can add an empty Segment in a different way or add an arbitrary number of empty Segments. It would seem cleaner to me to just allow multiple end joins.

**Comment by haussler** [comment]
This gets into a longer discussion I won't pursue completely here.
Richard's original model, which we have adopted and we like very much,
started with a primary reference sequence (e.g. the primary path of
chromosome 1 of GRCH38), and then sequentially added variants. (I use the
term "variant" here in a generic sense). Each variant added is a child to
the preexisting existing reference graph structure. Each new child is
specified by a DNA sequence (possibly empty) and a join at each end
indicating where it links in to the parent reference structure.

It is true that this approach yields some asymmetries in the particular
graph that represents the otherwise symmetric case that you discuss. These
asymmetries come about from the fact that you start with AB as the
reference sequence and then add variants on top of that.  However, the
benefits of having each additional variant be simple, with just one join on
either end, and there being a natural hierarchy of variants starting from
the default primary path and then moving on the more and more obscure
variants, outweighs the drawbacks of losing some symmetry.

-D

**Comment by lh3** [comment]
In summary, some generic sequence graphs cannot be converted to GA4GH graphs unless we introduce empty/zero-length segments, but if we allow empty-segments, we can convert the same generic graph to multiple equivalent GA4GH graphs. I guess this is a property of our graphs.

**Comment by richarddurbin** [comment]
I saw Hengs post about A,B,C,D yesterday, and nearly replied but wanted to think some more.
On reflection I suggest to go as the latest exchange between David and Heng says, i.e. to allow empty segments and stick with single joins.
I think that multiple end joins make things quite a lot more complicated for code, and that for any of these multiple sequence representations there are in practice alternative representations.  Already with the GA4GH style there is a choice at the start which to make the primary sequence from which others branch.  I stilll think that the single joining, and having a long primary sequence and adding things off that (and potentially arbitrary further things off those etc., which are likely to be rarer and shorter) are good ways to go.
Good discussion though.
I am going to spend next week in Santa Cruz, during which I aim to catch up with all the interface discussion.  I support in general the movement to get on an implement something and get practical experience, but have not followed all the detailed proposals recently.

**Comment by adamnovak** [comment]
@lh3 Yes, that's pretty much correct. We already have to deal with equivalent graphs, though: if you want to represent two genomes, and one has a SNP relative to the other, which version of the SNP is the primary path and which is the new one-base segment depends on which genome you start with.

We also need the empty segments for adding in things like inversions of parts of existing sequences.

I think this is going to work fine. If it isn't going to work fine, we need to implement it so we can find that out.

**Comment by ekg** [comment]
Having done a bit of work with reference graphs I am increasingly convinced
that it is easier to focus on the reference system as a collection of
sequences without preference toward any particular one. The idea of a
primary path is really not something that should be baked into the design
of the system. The reason is that you may want to change the primary path
later. In fact this is one of the major benefits of the system.

I'm not offering any solutions in terms of the GA4GH graph. But I do have
an implementation that doesn't have an intrinsic concept of the primary
path. Just paths in general. That is enough to represent almost everything
of interest. An reference genome becomes a path, as does any other
particular genome. An alignment is a path wrapped in metadata. Genomic
annotations are also paths.

Perhaps it is OK to simply establish a base graph using a versioning
system. Then we don't need to worry about the particular order in which
sequences were added to it. All sequences can be equivalently described as
paths through the graph. Updating the graph version would imply a
graph-graph alignment, which could be used for lift over of material
aligned to the old version.

This approach is advantageous in that it is expedient (for instance, I was
already able to implement all but the lift over part) and also it matches
existing intuition in the field about how reference genomes work. They have
releases and the releases have versions. Its OK if *some* pieces of the
reference are totally revised from one revision to the next. We may not
achieve the append only mode aimed for by the current model.

**Comment by selewis** [comment]
+1
(akin to the ancient discussions about whether there really is such a thing
as wildtype)

**Comment by jeromekelleher** [comment]
Closing this issue, as it is too general.
