### ISSUE TITLE
CORS tests are broken.

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#278]
Since Flask-CORS was updated recently, our test case for CORS support is failing (`testCors` in `tests/unit/test_views.py`). Why? I don't really understand what we're actually doing here, so I don't feel particularly qualified to comment on this.

**Comment by dcolligan** [comment]
I don't really get why CORS is necessary for our project.  Reading the Wikipedia page it seems like CORS only applies to browsers that want to pull resources from servers other than where the original web page was loaded.  That is, it is a way of getting around the same-origin policy in a policy-based way.  Can't we just remove it?

http://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by dcolligan** [comment]
Looking at the original proposal to incorporate CORS, it seems like someone wanted to develop a javascript client eventually.

https://github.com/ga4gh/server/issues/4

Presumably that's a long way away, so should we just remove CORS support entirely, since it seems to be causing us repeated headaches?

**Comment by jeromekelleher** [comment]
We need CORS for the existing JS compliance tester, and it was a feature request. We should try to figure out what the problem is here and sort if out.

**Comment by dcolligan** [comment]
Fixed in #282
