### ISSUE TITLE
Server CLI programs should follow Unix conventions

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#332]
Language of implementation should be hidden by the server CLI programs.  This  abstraction is one of the fundamental tenets of UNIX.  One shouldn't have to know what language a program is in use it.

     python ga4gh-demo.py

should be simply

    ga4gh-demo

programs should be in a directory `bin'

[you can have my UNIX when you pry it out of my cold, repetitive strain injured hands]

**Comment by jeromekelleher** [comment]
Yes, I agree that _programs_ should hide the language. That's why all the real CLI programs do this (ga2vcf, ga2sam, ga4gh_server, ga4gh_client). They aren't stored in a bin directory because they are made in a platform independent way by setuptools, so we never have to worry about installing them properly. Python does this for us.

These are _scripts_. They are either development tools intended to be run locally by developers, or (in this case) a throwaway script to demonstrate that the Python client API works. These should not get the same treatment as first-class programs that we distribute to users.

(And you can pry _my_ UNIX out of my cold hands too!)

**Comment by diekhans** [comment]
I didn't try it, I just read the doc! So maybe this is a
documentation ticket.

**Comment by jeromekelleher** [comment]
Which bit don't you like, the `ga4gh-demo.py` bit? This is just a script we're asking the user to make so they can run the Python code in the demo. We could get rid of the suffix, but then we'd have to put in a shebang in the script, and then say

Then run ``chmod u+x ga4gh-demo`` and run ``./ga4gh-demo``. I think putting it into a Python source file and just running it with the interpreter is a lot less confusing...

**Comment by diekhans** [comment]
Oh, so pre-install.  No problemo, close away.  Sorry for the noise!

**Comment by jeromekelleher** [comment]
No worries @diekhans, it's good to know you're keeping an eye on these things!
