### ISSUE TITLE
Allow server to start without all data directories existing

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#354]
Currently, if `DATA_SOURCE` is specified in the config, it must have a variants, reads and references directory.  We should probably be able to start the server with only subsets of these existing (for instance, if a user only wants to server read data).  What are the configurations that we should allow?  Currently this limitation can be circumvented by adding empty directories.

**Comment by jeromekelleher** [comment]
I guess:

2. reads/references
1. reads/references/variants

I think there should always be references for reads, since the reads are aligned against a particular reference, which should be available through the API.

**Comment by macieksmuga** [comment]
Since graph references have a different data directory structure, I made a separate data subdirectory, `graph_references`, to hold them for a graph reference server in my [graph prototype code](https://github.com/macieksmuga/server/tree/graphproto). While I'm not attached to this solution (the more I think about it, the less I like it), it will still affect the suggested mechanism above if we stick with it.

**Comment by dcolligan** [comment]
Closing this since it's not very compelling and the graph changes may complicate things... all in all, too little reward for the effort IMHO.
