### ISSUE TITLE
Re-enable & fix unit tests in test_views.py for schemas_e6d6074

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#358]
PR #353 cleanup

**Comment by dcolligan** [comment]
`testReadsSearch` is throwing a `ResponseValidationFailureException` because the `SearchReadsResponse` is failing avro validation.  Unfortunately, `avrotools` can only tell us that the `alignments` field is invalid, which is everything in the payload except for `nextPageToken`.  This would probably be a good time to modify `avrotool` to do recursive analyses instead of a depth=1 analysis.

**Comment by dcolligan** [comment]
See the `validate` function here https://github.com/apache/avro/blob/trunk/lang/py/src/avro/io.py#L101

**Comment by macieksmuga** [comment]
closed in #363
