### ISSUE TITLE
Re-enable & fix datadriven test_reads.py for schemas_e6d6074

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#360]

**Comment by dcolligan** [comment]
Multiple tests failing here.  `testGetReadAlignmentsBothRefs` can be eliminated since api changes have rendered it irrelevant.  `testValidateObjects` is likely suffering from the same problems as other tests -- reads validation is failing.  `testGetReadAlignmentsRefName` can also be eliminated since api changes have rendered it irrelevant.  `testGetReadAlignmentsStartEnd` and `testGetReadAlignmentSearchRanges` should be converted to use refIds instead of refNames.

**Comment by macieksmuga** [comment]
Closed in #363
