### ISSUE TITLE
readthedocs for develop

### ISSUE THREAD

**Issue by afirth** [ga4gh/server#381]
Please consider adding an RTD build for the develop branch. Should be accessible to admins at https://readthedocs.org/dashboard/ga4gh-reference-implementation/versions/

**Comment by jeromekelleher** [comment]
Any objections to this? We could make it point to 'latest' but keep the default as 'stable'.

**Comment by skeenan** [comment]
Can we make it so you don't have to create a readthedocs account in to see
this?

**Comment by jeromekelleher** [comment]
We have to a have a readthedocs account to get access to the control panel @skeenan. I'm happy to add you as an admin if you make an account though.

**Comment by pgrosu** [comment]
@jeromekelleher, @afirth It might be a good idea to keep it open for everyone to comment, since based on [the following link](https://github.com/ga4gh/server/blob/5d0a0faec6bfa1aff0f9a47e727ad57f3a822dfa/docs/source/development.rst) it mentions "*All development is done against the develop branch"*, but does not require special access for any parts of the code.

**Comment by dcolligan** [comment]
"We could make [develop] point to 'latest' but keep the default as 'stable'." +1 

What is the difference between what latest and stable point to now on RTD?

**Comment by jeromekelleher** [comment]
@dcolligan 'latest' points to master right now. Shall I flip this over to the develop branch?

**Comment by dcolligan** [comment]
Stable should point to master, since master is stable (and the version that has been released on pypi).
Latest should point to develop.

**Comment by dcolligan** [comment]
What is the process for updating docs on readthedocs?  We don't need to take some manual action for every commit to develop, do we?

**Comment by afirth** [comment]
@dcolligan no manual intervention needed, just change the branch that the develop points to. Or, check the box on the dashboard to make develop an active build. Much like travis, you can set it up to build on any endpoint it recognizes

**Comment by dcolligan** [comment]
Cool.  Assigning to @jeromekelleher, since he set this up and presumably has access.

**Comment by jeromekelleher** [comment]
OK, there is now a 'develop' version on readthedocs:

http://ga4gh-reference-implementation.readthedocs.org/en/develop/

This will rebuild every time we push an update to the develop branch. 

For reference, the other versions are 'stable', which points to the most recent version tagged on github (or we can assign a specific tag) and 'latest', which points to master.  I couldn't figure out how to make 'latest' point to our develop branch, and anyway, I think this is better. We're clearly highlighting that these docs are from the bleeding edge by calling the version 'develop' rather than 'latest'. In the future, we might imagine having 'stable' point to an older release, which is nice and stable and and 'latest' point to the latest release which is a beta.

What do we think?

**Comment by pgrosu** [comment]
Thanks @jeromekelleher :)

**Comment by dcolligan** [comment]
That's fine with me.
