### ISSUE TITLE
/variantsets/search allows nonsense requests

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/server#460]
It seems no matter what I request, I always get all info on both variantSets in the example-data::

    curl --data '{"id":["1kg-phase1"]}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/variantsets/search 
    curl --data '{"utter":["nonsense"]}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/variantsets/search

It seems the server should return info on one set in the first example (though I think you can only search on DatasetId, which isn't implemented), and an error in the second.

I'm using commit 5be6c026dbec73a23467054a838f1aeff75524ba

**Comment by jeromekelleher** [comment]
Neither of these is actually a well formed query @Jeltje --- 'id' is not a valid member of [GASearchVariantSetsRequest](http://ga4gh.org/documentation/api/v0.5.1/ga4gh_api.html#/schema/org.ga4gh.GASearchVariantSetsRequest) in 0.5.1. In both cases, you've provided a malformed query, but have not gotten an error response back because `REQUEST_VALIDATION` is set to False by default. If you provide a configuration file when starting the server, and set this value to True, the server sends back an error in this situation.

The reason that REQUEST_VALIDATION is set to False in the released version (in case you are wondering) is because the [compliance tester](https://github.com/ga4gh/compliance) sends some queries that do no pass JSON validation, which gives us lower conformance scores if we respond correctly to them.

**Comment by diekhans** [comment]
Jerome Kelleher <notifications@github.com> writes:
> The reason that REQUEST_VALIDATION is set to False in the released version (in
> case you are wondering) is because the compliance tester sends some queries
> that do no pass JSON validation, which gives us lower conformance scores if we
> respond correctly to them.

Seems like the compliance tester needs unit tests ;-)

This will be fixed with the new compliance suite
