### ISSUE TITLE
Back out of doc change on stable?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#478]
PRs adding new features should  be made against the `develop` branch and we should only merge into the `stable` branch after we've made a release. PRs #471 and #477 were made against the 'stable' branch and not 'develop' as they should have been. I didn't pay attention to the branch that the PRs were being made against and merged them, so this is mainly my responsibility.

How should we resolve this?

**Comment by dcolligan** [comment]
We can either:
1) do nothing, especially since these are non-code changes
2) force push the stable branch to the last released commit (`12b093b31bb24f4ba7853300b32dfb11c44408f7`)
3) push a couple of reverted commits to stable

2 would be most correct from a "make the released code match the branch" standpoint, but has the downside of making a non-fast-forward commit to the stable branch.

**Comment by jeromekelleher** [comment]
(2) is probably not something we should do, since someone might have based a branch off stable and force pushes are bad form in this case. So, I guess (3) is the right thing to do, coupled with cherry picks of the relevent commit back to develop?

**Comment by dcolligan** [comment]
Ok, I'll submit a PR to each branch to implement 3 now

**Comment by dcolligan** [comment]
See #482 for the stable revert and #483 for the change to the develop branch

**Comment by dcolligan** [comment]
Fixed
