### ISSUE TITLE
Error handling is required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#6]
Currently, any exceptions that occur are not dealt with. At a minimum, we need to catch these exceptions and send back a GAException object to the client. See the TODO section of the README for further discussion of this.

**Comment by jeromekelleher** [comment]
We are now in a position to start dealing with errors properly, so it would be good to discuss the basic approaches we might take. One method would be to define a new module `ga4gh.exceptions` that contains all the exceptions that can occur. For example, we might have a hierarchy like
```
Exception 
    ga4gh.exceptions.GAException 
             ga4gh.exceptions.InvalidPageToken
             ga4gh.exceptions.InvalidDataSetId
             ga4gh.exceptions.InvalidVariantSetId
             ...
  ```
These exceptions then have an error message and errorCode associated with them, which are used to generate the relevant `ga4gh.protocol.GAException` object by the frontend. 

Does this sound like a reasonable approach?

**Comment by dcolligan** [comment]
NB: there is not TODO section of the README anymore

Assuming these are all errors that would be returned to the client, each should also have a corresponding HTTP code.

Also, if we're worried about i18n, we should externalize the messages (not sure if this is a concern).

**Comment by diekhans** [comment]
Given that this is a reference server, we should not implement
i18n.  It's important to avoid the complexities of a production
server so that it can fulfill it's primary mission well.

Mark

**Comment by jeromekelleher** [comment]
I agree with @diekhans here - i18n isn't a priority. I'm not sure what the correct approach regarding HTTP codes is: presumably, we set a generic HTTP error code saying something nasty happened, and also return the JSON `GAException` object which gives the details?

**Comment by diekhans** [comment]
I think:
  - invalid input: 400 "Bad Request"
  - search not found:  404 "Not Found"
  - general error: 500 "Internal Server Error"

all with more GAException in body, I think.. (but I haven't looked at
how the search requests protocols are specified).

**Comment by dcolligan** [comment]
We'll need to iterate on these a bit (especially because the schema is not finalized), but I think this general approach to the hierarchy would be good:
```
Exception 
    ga4gh.exceptions.GAException 
             ga4gh.exceptions.BadRequestException (400)
                     ga4gh.exceptions.BadPageSize
                     ga4gh.exceptions.BadPageToken
             ga4gh.exceptions.NotFoundException (404)
                     ga4gh.exceptions.PathNotFound
                     ga4gh.exceptions.ObjectNotFound
             ga4gh.exceptions.ServerException (500)
             ...
```

I don't think we need to bother with success error codes other than 200, at least not until clients can create/modify/delete objects on the server.  In that case, maybe we want to still go with 200 for all successful requests or perhaps some other scheme involving other 2xx status codes.

At the same time, there should be some central registry of error codes.  Each error has the following fields:

- Error code (like GAE0000005 or whatever, or perhaps a more descriptive one like A_PARTICULAR_ERROR)
- English language message (can change, as opposed to other fields which are locked in with the API release)
- Exception in the hierarchy (and implied HTTP status code)
- Optional: extended English explanation of error

Now the question is, how do we want to put all of this into exceptions.py?  I can see three approaches:
1) manually entering everything in as python objects
2) sticking the data in some array or dict in exceptions.py that is then read into objects at startup
3) having all the data in YAML or some other format that gets preprocessed into the automatically generated exceptions.py

Thoughts?

**Comment by jeromekelleher** [comment]
This looks great @dcolligan, thanks for fleshing it out. Two comments:

1. After looking at the Python exception hierarchy (https://docs.python.org/3/library/exceptions.html#exception-hierarchy)  again, I wonder if we should use the `Error` suffix for consistency. The distinction here is that Exceptions are used for more than just error handling. So, we'd have `RequestError`, `PageSizeError`, `PageTokenError` etc. We could then make the root exception `ServerError`, which would avoid the unfortunate name clash with `protocol.GAException`. I'm not sure if this is better or not, it's just a suggestion for discussion.

2. I would suggest doing everything manually as Python objects for now. Lets see how it develops and we can always move to something more sophisticated later if we need to.

**Comment by dcolligan** [comment]
Well, I think it's good to use *Exception or *Error consistently.  The means either naming everything *Exception, or changing the schema to rename `protocol.GAException` to `protocol.GAError`

**Comment by jeromekelleher** [comment]
I agree that we should definitely use either *Exception or *Error consistently. I don't see why we'd need to change the protocol if we were to use the `Error` convention for our internal use though. There will ever only be one protocol Exception class, which we represent internally as `protocol.GAException`. This class doesn't extend `Exception`, isn't part of our internal exception hierarchy, and is used only to format error messages to the clients. 

I'd like to get other's views on this - who prefers '*Exception' or '*Error'?

**Comment by pashields** [comment]
@jeromekelleher are you saying there would ```protocol.GAException``` and ```exceptions.GAError```?

**Comment by jeromekelleher** [comment]
Well, I was thinking more along the lines of having `ServerError` as the root of the hierarchy of exceptions that happen in the server. I don't really mind though, I'm just bringing up the point for discussion.

**Comment by pashields** [comment]
If the exceptions hierarchy being proposed by @dcolligan is only for the frontend, we shouldn't put it in a standalone module. I'm more concerned about what the specified hierarchy here is than the naming. And I would argue that these exceptions really should be for the frontend only. A file not found is not necessarily a 404 (a missing sqlite database for instance). Conflating internal and external errors can lead to unnecessary coupling between the frontend and backend(s).

**Comment by jeromekelleher** [comment]
Good point @pashields - should we just define these frontend exceptions in the frontend module then?

Where do you stand on *Exceptions vs *Error?

**Comment by dcolligan** [comment]
@pashields +1 on decoupling frontend and backend errors (`PathNotFound` was meant for a URL path)

Another option is just to stick to having just one GAException type and let the clients drive their behavior off of the errorCode alone instead of any type hierarchy.

**Comment by diekhans** [comment]
chained exceptions  (cause field) are the single best error handling approach I have used and would be very valuable in the server.  However, these are only available in python 3.

My implementation for python 2 is here:
http://hgwdev.cse.ucsc.edu/~markd/ga4gh/PycbioException.py

**Comment by jeromekelleher** [comment]
I think we have to have just one `GAException` type for the protocol --- clients will have to work with the `errorCode` as you say. How we structure our *internal* exception hierarchy is independent of this, I think, once we can map back to `errorCode` and `message` attributes for the client.

**Comment by pashields** [comment]
Upon thinking about this a bit more, I'd push for our internal exceptions to be GAException rather than GAError. My reasoning for this is that the protocol itself defines the notion of an error which, as we've discussed above, is separate from our notion of and internal/error exception. If we keep our internal exceptions as, well, exceptions, I think it will bring some linguistic clarity to future discussions.

**Comment by dcolligan** [comment]
I think @pashields's Error/Exception distinction being the same as the External/Internal distinction is a good idea.

The only issue I see remaining reading over this thread is @pashields 's concern about having the exceptions in `exceptions.py` rather than `frontend.py` ... thoughts?

**Comment by jeromekelleher** [comment]
Good, I'm happy with that conclusion. 

I think we have to put the exceptions somewhere other than `frontend.py`, and `exceptions.py` might be as good as any for now. We can't define the exceptions in `frontend.py` because we would have to import `frontend` in `backend.py` and all the `datamodel` modules. This seems like unnecessary coupling to me. If we define the exceptions locally in `backend` and all the `datamodel` modules, then we'll have to import all of these modules into `frontend.py` which is also very tight coupling. By using `exceptions.py`, this becomes a standard import in all files, and we're always sure that the class definitions are available. I'm probably missing some point here though...

**Comment by pashields** [comment]
My point was just that if exceptions.py is only holding frontend exceptions, they should be in frontend. The backend shouldn't ever import the frontend exceptions, so that's not a problem. If we want to put all our exceptions into a single file, exceptions.py would be the place to do it. I'm not sure what the most idiomatic way to do it in python is. My only concern with group things together is that we have to be much more vigilant in PRs to prevent the backend from looking at frontend exceptions.

**Comment by dcolligan** [comment]
Ok, two proposals for moving forward; everyone choose one:

1) put frontend exceptions in `frontend.py` and (future) backend exceptions in `backend.py` and eliminate any `exceptions.py` file

2) create `frontend_exceptions.py` and `backend_exceptions.py` files which are imported by the appropriate modules

Personally, I like (2) just from an aesthetic code organization perspective.

**Comment by dcolligan** [comment]
Closing this issue for now, since #88 has been merged and "we should use exceptions more" is too vague for an issue
