### ISSUE TITLE
Remove remote fetch functionality

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#612]
The urls.json remote fetch scheme is hacky, and also we've recently discovered that htslib's remote fetch has bugs wrt fetching from an overloaded server.  Therefore this feature not ready for production in the ga4gh server.  We can reinstate this functionality when the htslib issues are fixed (and when pysam supports writing a remote index file to somewhere other than the current directory).

See #500

**Comment by jmarshall** [comment]
Eh?  What you've recently discovered is that fetching data from an overloaded server is unreliable.  HTSlib's (really knetfile.c's) current way of reporting this (crashing) is less than ideal, but that's not the real problem.  The real problem is that overloaded servers are overloaded.

**Comment by jeromekelleher** [comment]
Have to disagree with you here @jmarshall --- crashing under any circumstances is a bug, full stop. We depend on htslib sending us back error messages so we can diagnose what happens and deal with the problem. Crashing isn't error reporting, it's crashing. I don't think people would be too forgiving if glibc segfaulted or aborted under error conditions; we should have the same expectations for htslib.

So, I fully agree with @dcolligan. Since the remote read code currently isn't reliable and can lead to a user request crashing our server (which has serious security implications), we must disable our use of this feature.

**Comment by dcolligan** [comment]
Fixed in #605
