### ISSUE TITLE
Pick schemas up directly from repo

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#660]
Related to compliance issue https://github.com/ga4gh/compliance/issues/101, the schemas should be picked up directly from their repo on every build. This will assist with automating continuous integration between all three GA4GH repos (Schemas/Server/Compliance)

**Comment by dcolligan** [comment]
-1

We don't want a screwup (or, even an expected but incompatible change) in the schemas to fail our build.  We pin the versions of all the external libraries we are using for the same reason.

**Comment by jeromekelleher** [comment]
-1 also. This would be difficult to do in practise, and would make workflows very brittle and slow. At least while we have Avro, I don't think this is practical or desirable. It would also lead to chicken and egg situations --- our build is failing because we can't get the schemas into master, but our schemas can't get into master until we have something working in the reference server.

**Comment by hjellinek** [comment]
-1 for the reasons you cite.  I commented on the Compliance counterpart of this issue [here](https://github.com/ga4gh/compliance/issues/101) - I'd be interested in your take on that.
