### ISSUE TITLE
Problem setting up project

### ISSUE THREAD

**Issue by gabrielsaldana** [ga4gh/server#805]
I'm trying to set up a development environment with Docker following the current documentation at http://ga4gh-reference-implementation.readthedocs.org/en/latest/installation.html#deployment-on-docker but ran into some issues:

After docker image build, running: docker run myimage Outputs an error: OSError: [Errno 2] No such file or directory: '/ga4gh-example-data/referenceSets'

The link for the example data at http://www.well.ox.ac.uk/~jk/ga4gh-example-data.tar.gz is broken

After trying another command: docker run -d -p 8000:80 --name ga4gh_demo afirth/ga4gh-server:develop-demo Got error: Error pulling image (develop-demo) from docker.io/afirth/ga4gh-server, Untar re-exec error: exit status 1: output: write /data/ga4gh-example-data/reads/low-coverage/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam: no space left on device

Am I missing something from the documentation or does the docs need more details or an update?

**Comment by jeromekelleher** [comment]
Thanks for the bug report @gabrielsaldana. The problem here is that our released version of the server is now very different to the development version of the server, and the documentation is now very confusing in terms of which version it refers to. Also, the docker setup isn't being maintained as well as it might be as we don't have any continuous integration testing for it currently.

For your specific issue here, I think you can try either the `latest' build with the example data at  http://www.well.ox.ac.uk/~jk/ga4gh-example-data.tar (no .gz), or you can also try the `develop' using the http://www.well.ox.ac.uk/~jk/ga4gh-example-data-v3.0.tar data file.

We should have updated to a new alpha release in the next day or two, and hopefully will have a stable release to follow up soon. This should resolve the current documentation mess.

**Comment by david4096** [comment]
I think you were able to get past this @gabrielsaldana, please feel free to reopen otherwise.
