### ISSUE TITLE
Use hgvs library for HGVS operations?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#841]
In methods such as `convertLocationHgvsP` in ga4gh.datamodel.variants we seem to be doing some regex parsing. Is this implementing HGVS? If so, can we use the [hgvs](https://pypi.python.org/pypi/hgvs/0.4.4) module to do this? Otherwise, we'll need to write some test cases for this functionality.

**Comment by david4096** [comment]
I took a look at the HGVS module and it seems like it's not what we're looking for right now. It brings in a lot of dependencies and doesn't offer the functionality we need without costly lookups.

This was brought up because we didn't have HGVS formatted genomic coordinates in annotated VCFs. Generating those coordinates requires mapping to a genome, so for now the VCFs will include the HGVS values before being added to GA4GH.

Here are the new test data:

https://github.com/ga4gh/compliance/pull/162

Suggest closing this one.

**Comment by jeromekelleher** [comment]
OK, thanks for looking into it @david4096.
