### ISSUE TITLE
Padding in identifiers

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#860]
There are equals signs (`=`) for padding base64 encoded identifiers that are leaked to returned identifiers. Normal practice is for `=` to encode key-value pairs in a query string. `=` is a reserved character for URL strings so our GET by ID requests look odd. 

     http get localhost:8000/referencesets/aGczNw%3D%3D (is the same as)
     http get localhost:8000/referencesets/aGczNw==

Perhaps the padding should be optional, for example, why are `YnJjYTE6SEcwMDA5Ng==`, `YnJjYTE6SEcwMDA5Ng=`, `YnJjYTE6SEcwMDA5Ng` considered three separate identifiers?

A separate but perhaps related issue, there is no ceiling on the length of identifiers.

https://www.w3.org/Addressing/URL/4_URI_Recommentations.html

**Comment by dcolligan** [comment]
Manipulating opaque identifiers is probably a bad idea (our ID scheme will perhaps change in the future).  Also, we can't just strip off the equals since that causes the decode to fail because of incorrect padding:
```
>>> import base64
>>> base64.b64decode("YnJjYTE6SEcwMDA5Ng==")
'brca1:HG00096'
>>> base64.b64decode("YnJjYTE6SEcwMDA5Ng=")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
>>> base64.b64decode("YnJjYTE6SEcwMDA5Ng")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```
If we're not url encoding our GET arguments, we should be.

True that there's no ceiling on the ID length, but at present I don't think that's going to be a problem in practice.  The max url length for a GET request is over 2000 characters.

**Comment by jeromekelleher** [comment]
Excellent point @david4096, well spotted. @dcolligan is right though, we can't just strip off the trailing '=' characters. Options:

1. Require IDs specified in GET URLs be url-encoded, but leave our IDs in their current form;
2. URL encode all our IDs at source.

I don't have a strong opinion here; what do we think?

**Comment by dcolligan** [comment]
I vote for 1

**Comment by david4096** [comment]
Perhaps we can avoid leaking the `=` to the user by adding padding ourselves?

        import base64
        def safe_b64_decoder(data):
          missing_padding = (4 - len(data) % 4) %4
          if missing_padding == 3: 
          	data += b'A=='
          elif missing_padding == 1 or missing_padding == 2: 
          	data += b'=' * missing_padding 
          return base64.b64decode(data)

http://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding

**Comment by jeromekelleher** [comment]
Can you elaborate on this a bit @david4096?

**Comment by david4096** [comment]
Since one can programmatically add or remove padding I can conceive of a mechanism that hides the padding from returned identifiers. One might remove the `=` before returning an ID to the user and adding them again when a request is received.

**Comment by jeromekelleher** [comment]
OK, I guess this is an option, and possibly the least unpleasant one. Requiring clients to URL encode the IDs seems like a hard requirement. It seems like the schema should require that all IDs are URL safe, since we are going to be constructing these GET URLs.

Can you follow up on this with a PR please @david4096,  so we can see how it looks? The changes required should be fairly small. If it looks good we should also open a PR against the schemas documentation with the requirement that all IDs are URL safe.

**Comment by diekhans** [comment]
Sigh, while conceptually I believe that one should always URL
encode when generating a URL, in practice, most of us don't.
Especially since the command line tools don't do it for you.

Making ids safe is probably a good idea.  @david4096, can you do
pull request against the overview documentation to define it?

**Comment by david4096** [comment]
#872 treats this on the server side and it seems to pass all the nosetests.

**Comment by diekhans** [comment]
definition of id is in doc/source/api/apidesign_intro.rst  
please update this if require id to be unique

**Comment by diekhans** [comment]
please note python function base64.urlsafe_b64encode

**Comment by dcolligan** [comment]
The `urlsafe_*` functions do this (from the docs): `The alphabet uses '-' instead of '+' and '_' instead of '/'.`  The padding character is the same.

**Comment by diekhans** [comment]
What ever encoding is used, it must be idempotent for URL encoding. 

What about removing the padding after urlsafe_b64encode and
adding it back in before decoding?

**Comment by diekhans** [comment]
discussion as to why urlsafe_b64encode is the way it is!

https://bugs.python.org/issue1661108

**Comment by jeromekelleher** [comment]
@diekhans --- interesting! I think we're still safer stripping the '=' character from the IDs though.

Also, #872 is addressing this directly --- let's move discussion over there.

**Comment by diekhans** [comment]
yes, urlsafe_b64encode isn't enough because it oddly leaves in the `='

**Comment by david4096** [comment]
Discussion in schemas

https://github.com/ga4gh/schemas/pull/542
