### ISSUE TITLE
Dependency test issue within test_imports.py

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#887]
When implementing sequence annotations, we created `ga4gh/gff3.h` as a parsing library for the gff3 file format. It is being used within the codebase for `ga4gh/datamodel/sequenceAnnotations.py` - but as such, it fails the dependency checks in `tests/unit/test_imports.py`:
```
PolicyException: module 'ga4gh/datamodel/sequenceAnnotations.py' in moduleGroup 'datamodel' has dependency on module 'ga4gh/gff3.py' in moduleGroup 'libraries'
```
Now, as far as I understand it, a library contains code that is used in higher application layers, so I thought this was just an accidental mis-ordering of dependencies. But when I reversed that part of the dependency graph (so that `datamodel` can use code from `libraries` but not vice versa), I got this:
```
PolicyException: module 'ga4gh/converters.py' in moduleGroup 'libraries' has dependency on module 'ga4gh/datamodel/reads.py' in moduleGroup 'datamodel'
```
Which breaks my understanding of what a code library is meant to be here, and prevents me from writing actual library-like modules for use within `datamodel` code.

**Comment by diekhans** [comment]
@macieksmuga please comment this out until @dcolligan can resolve this.

**Comment by jeromekelleher** [comment]
I agree with @diekhans.

**Comment by macieksmuga** [comment]
@saupchurch proposed a simple workaround for now, placing the `gff3` parser in the `datamodel` module group until the underlying issue is resolved.

**Comment by dcolligan** [comment]
@macieksmuga can you point me to a branch where you see this error so I can reproduce it?

The moduleGroup name `libraries` is just a name... we can rename it to whatever we want.  The first error seems to be a correct operation of `test_imports`.  The second error you listed seems incorrect: `converters.py` should be able to call into `reads.py` since `libraries` is in a layer above `datamodel`.  Indeed, this is the case in the code in the `master` branch and no error is thrown.  Of course, there could be a bug in the test somewhere...

**Comment by david4096** [comment]
I think this got "fixed" here:

https://github.com/ga4gh/server/pull/924

@dcolligan @macieksmuga ?

**Comment by dcolligan** [comment]
I just re-enabled the test in that PR.  If the test is actually failing elsewhere, they're two different issues.  If one can point me to a branch where it is failing (if one exists), I can attempt a fix.

**Comment by dcolligan** [comment]
Looks like this is not an issue anymore
